---
name: Docker Image CI

on:
  workflow_call:
    inputs:
      fail-on-error:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t my-image:latest .

      - name: Run tests in the Docker container
        run: |
          docker run --rm my-image:latest /bin/bash -c "echo 'Running tests