---
name: Docker Image CI

on:
  workflow_call:
    inputs:
      fail-on-error:
        required: false
        type: boolean
        default: true
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t my-image:latest .

      - name: Run tests in the Docker container
        run: |
          docker run --rm my-image:latest /bin/bash -c "echo 'Running tests'"