---
name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t my-image:latest .

      - name: Run tests in the Docker container
        run: |
          docker run --rm my-image:latest /bin/bash -c "echo 'Running tests