name: Trailing Whitespace

on:
  workflow_call:
    inputs:
      fail-on-error:
        required: false
        type: boolean
        default: true
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
jobs:
  lint-trailing:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for trailing whitespace
        run: |
          if grep -rI --exclude-dir=.git '[[:space:]]$' ./; then
            echo "Trailing whitespace found!"
            exit 1
          else
            echo "No trailing whitespace."
          fi
